feat: add support for harmony bech32 address
Cypherock/cysync-module-protocols pull request #60
Opened 2022-12-12 14:26 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/37308523/CSI-1480

2022-12-12 14:34 UTC, irshadCypherock requested changes

2022-12-12 14:34 UTC, irshadCypherock commented on src/flows/receiveTransaction/index.ts
> +            coin.coinListId === 0x0e
Avoid hard coding the `coinListId`

2022-12-13 05:41 UTC, ujjwal-cyph commented on src/flows/receiveTransaction/index.ts
> +            coin.coinListId === 0x0e
`coin.coinListId === ETHCOINS['one'].coinListId`

is this a better choice?

2022-12-13 07:44 UTC, irshadCypherock approved these changes

2022-12-13 07:44 UTC, merged